CREATE TABLE CITAS
(
    ID                      VARCHAR(15),
    MEDICO_ID               VARCHAR(9),
    PACIENTE_ID             VARCHAR(8),
    DOSIS                   NUMERIC(5),
    FRECUENCICA             NUMERIC(5),
    UNIDAD                  VARCHAR(15),

    CONSTRAINT "PK_CITAS"                    PRIMARY KEY (ID),
    CONSTRAINT "NN_CITAS.MEDICO_ID"          CHECK (MEDICO_ID IS NOT NULL ),
    CONSTRAINT "NN_CITAS.PACIENTE_ID"        CHECK (PACIENTE_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.DOSIS"              CHECK (DOSIS IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.FRECUENCICA"        CHECK (FRECUENCICA IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.UNIDAD"             CHECK (UNIDAD IS NOT NULL ),
    CONSTRAINT "CH_POSOLOGIA.UNIDAD"             CHECK (UNIDAD IN ('MILIGRAMOS', 'MILILITROS', 'GOTAS')),

    CONSTRAINT "FK_CITAS.MEDICO_ID"      FOREIGN KEY (MEDICO_ID)    REFERENCES MEDICO(DIN),
    CONSTRAINT "FK_CITAS.PACIENTE_ID"    FOREIGN KEY (PACIENTE_ID)  REFERENCES PACIENTE(CIPAUT),
);