CREATE TABLE POSOLOGIA
(
    ID                      VARCHAR(15),
    MEDICO_ID               VARCHAR(9),
    PACIENTE_ID             VARCHAR(8),
    MEDICINA_ID             VARCHAR(15),
    DOSIS                   NUMERIC(5),
    FRECUENCICA             NUMERIC(5),
    UNIDAD                  VARCHAR(15),

    CONSTRAINT "PK_POSOLOGIA"                    PRIMARY KEY (ID),
    CONSTRAINT "NN_POSOLOGIA.MEDICO_ID"          CHECK (MEDICO_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.PACIENTE_ID"        CHECK (PACIENTE_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.MEDICINA_ID"        CHECK (MEDICINA_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.DOSIS"              CHECK (DOSIS IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.FRECUENCICA"        CHECK (FRECUENCICA IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIA.UNIDAD"             CHECK (UNIDAD IS NOT NULL ),
    CONSTRAINT "CH_POSOLOGIA.UNIDAD"             CHECK (UNIDAD IN ('MILIGRAMOS', 'MILILITROS', 'GOTAS')),

    CONSTRAINT "FK_POSOLOGIA.MEDICO_ID"      FOREIGN KEY (MEDICO_ID)    REFERENCES MEDICO(DIN),
    CONSTRAINT "FK_POSOLOGIA.PACIENTE_ID"    FOREIGN KEY (PACIENTE_ID)  REFERENCES PACIENTE(CIPAUT),
    CONSTRAINT "FK_POSOLOGIA.MEDICINA_ID"    FOREIGN KEY (MEDICINA_ID)  REFERENCES MEDICINA(ID),
);