CREATE TABLE POSOLOGIAS
(
    ID                      VARCHAR(15),
    MEDICO_ID               NUMERIC(9),
    PACIENTE_ID             VARCHAR(13),
    MEDICINA_ID             VARCHAR(15),
    DOSIS                   NUMERIC(5),
    FRECUENCIA             NUMERIC(5),
    UNIDAD                  VARCHAR(15),

    CONSTRAINT "PK_POSOLOGIAS"                    PRIMARY KEY (ID),
    CONSTRAINT "NN_POSOLOGIAS.MEDICO_ID"          CHECK (MEDICO_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIAS.PACIENTE_ID"        CHECK (PACIENTE_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIAS.MEDICINA_ID"        CHECK (MEDICINA_ID IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIAS.DOSIS"              CHECK (DOSIS IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIAS.FRECUENCIA"        CHECK (FRECUENCIA IS NOT NULL ),
    CONSTRAINT "NN_POSOLOGIAS.UNIDAD"             CHECK (UNIDAD IS NOT NULL ),
    CONSTRAINT "CH_POSOLOGIAS.UNIDAD"             CHECK (UNIDAD IN ('MILIGRAMOS', 'MILILITROS', 'GOTAS')),

    CONSTRAINT "FK_POSOLOGIAS.MEDICO_ID"      FOREIGN KEY (MEDICO_ID)    REFERENCES MEDICOS(DIN),
    CONSTRAINT "FK_POSOLOGIAs.PACIENTE_ID"    FOREIGN KEY (PACIENTE_ID)  REFERENCES PACIENTES(CIPAUT),
    CONSTRAINT "FK_POSOLOGIAs.MEDICINA_ID"    FOREIGN KEY (MEDICINA_ID)  REFERENCES MEDICAMENTOS(ID)
);