### GET /relacciones/animales/{id}
GET http://localhost/aggregator/posologias/CYL0000000002

### GET /relacciones/animales/{id}
GET http://localhost/posologias/CYL0000000002


### GET /relacciones/animales/{id}
POST http://localhost:8080/secure
Content-Type: application/json

{
  "id": "CYL0000000006",
  "apellido": "Ruiz"
}
