### GET /relacciones/animales/{id}
GET http://localhost/aggregator/posologias/CYL0000000004

### GET /relacciones/animales/{id}
GET http://localhost/posologias/CYL0000000004


### GET /relacciones/animales/{id}
POST http://127.0.0.1:8083/secure
Content-Type: application/json

{
  "id": "CYL0000000006",
  "apellido": "Ruiz"
}

