CREATE TABLE PACIENTES
(
    CIPAUT                      VARCHAR(13),
    NOMBRE                      VARCHAR(100),
    APELLIDO1                   VARCHAR(100),
    APELLIDO2                   VARCHAR(100),


    CONSTRAINT "PK_PACIENTES"                    PRIMARY KEY (CIPAUT),
    CONSTRAINT "NN_PACIENTES.NOMBRE"             CHECK (NOMBRE IS NOT NULL ),
    CONSTRAINT "NN_PACIENTES.APELLIDO1"          CHECK (APELLIDO1 IS NOT NULL ),
    CONSTRAINT "NN_PACIENTES.APELLIDO2"          CHECK (APELLIDO2 IS NOT NULL )
);