CREATE TABLE PACIENTES
(
    CIPAUT                      VARCHAR(8),
    NOMBRE                      VARCHAR(100),


    CONSTRAINT "PK_PACIENTES"                    PRIMARY KEY (CIPAUT),
    CONSTRAINT "NN_PACIENTES.NOMBRE"             CHECK (NOMBRE IS NOT NULL )
);