mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem 

quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true

quarkus.smallrye-openapi.servers=/security

quarkus.swagger-ui.path=/security/swagger-ui
quarkus.swagger-ui.urls.default=/security/q/openapi
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include= true