quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}

quarkus.langchain4j.openai.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.chat-model.log-requests=true
quarkus.langchain4j.openai.chat-model.log-responses=true
quarkus.langchain4j.openai.chat-model.temperature=${model.temperature}
quarkus.langchain4j.openai.chat-model.frequency-penalty=${model.frequency}

quarkus.langchain4j.pgvector.dimension=1536
quarkus.langchain4j.pgvector.table=embeddings

model.temperature=0.5
model.frequency=0
model.results=3
model.score=0.6
model.memory=5


database.host=localhost
database.port:5432
database.name=upsa
database.username=system
database.password=manager


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${database.username}
quarkus.datasource.password=${database.password}
quarkus.datasource.jdbc.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}

mp.jwt.verify.publickey.location=publicKey.pem

quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.enable-forwarded-host=true

quarkus.swagger-ui.path=/backend/swagger-ui
quarkus.swagger-ui.urls.default=/backend/q/openapi
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include= true
