worker_processes auto;
events{
    worker_connections 1024;
}

http
{
    upstream ups_medicamentos
    {
        server ws-medicamentos:8080;
    }
    upstream ups_medicos
    {
        server ws-medicos:8080;
    }
    upstream ups_pacientes
    {
        server ws-pacientes:8080;
    }

    server
    {
        listen 80;
        server_name xxx.upsa.es;

        location /medicamentos
        {
            proxy_pass http://ups_medicamentos;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /pacientes
        {
            proxy_pass http://ups_pacientes;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /medicos
        {
            proxy_pass http://ups_medicos;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }

}